x-config: &val "prod"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  silo:
    image: pgsty/silo:RELEASE.2026-09-16T00-00-00Z
    container_name: silo
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=siloadmin
      - MINIO_ROOT_PASSWORD=siloadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mc:
    image: pgsty/mc:RELEASE.2026-09-16T00-00-00Z
    container_name: silo-init
    depends_on:
      silo:
        condition: service_healthy
    environment:
      BUCKET_NAME: *val
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set silo http://silo:9000 siloadmin siloadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing silo/$$BUCKET_NAME;
      exit 0;
      "
